### ISSUE TITLE
Build first draft of dashboard

### ISSUE THREAD

**Issue by JoaoCarabetta** [JoaoCarabetta/SimulaCovid#2]
dropdowns:
- Estado
- Município
- Respiradores / Leitos 

1. Em quantos dias vai dar merda --> quando acabarão os respiradores e leitos
2. O que fazer? 
    --> lockdown
    --> do nothing
    --> isolamento social
    --> lockdown + apoio saúde
3. Quantas vidas podem ser salvas com cada opção
4. Quanto tempo você ganha
--> parametros abertos
   -- numero de respiradores 
   -- numero de leitos

Tabela Parametros:
- R0 para cada caso e etc

Tabela Municipio:
- estado
- nome
- populacao

Tabela Capacidade Hospitalar
- estado
- municipio
- mes
- n_leitos
- n_ventiladores
- data atualizacao

Tabela Numero de Casos
- estado
- municipio
- mes
- dia
- n_casos 
- etc...

Tabela progagacao covid19
- estado
- municipio
- n_dias
- n_uti
- n_infectados

-- n_leitos
-- n_dias

**Comment by fernandascovino** [comment]
Draft: https://datastudio.google.com/s/pb9e8BGqHsI
