### ISSUE TITLE
Write documentation in Github

### ISSUE THREAD

**Issue by JoaoCarabetta** [JoaoCarabetta/SimulaCovid#7]
Methodology & articles: https://docs.google.com/document/d/1PLNF_vA84M2hAykU8bC3KQ-YmUA7Rju8IO0w9iTmcLg/edit

**Comment by fernandascovino** [comment]
@ap1631 se puder consolidar os estudos que cê mandou também no documento! 

Colocando aqui para não perder:

- [Evolving Epidemiology and Impact of Non-pharmaceutical Interventions on the Outbreak of Coronavirus Disease 2019 in Wuhan, China](https://www.medrxiv.org/content/10.1101/2020.03.03.20030593v1)
- [Severe Outcomes Among Patients with Coronavirus Disease 2019 (COVID-19) — United States, February 12–March 16, 2020](https://www.cdc.gov/mmwr/volumes/69/wr/mm6912e2.htm#T1_down)

**Comment by anappellegrino** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Métricas de acurácia do modelo](https://trello.com/c/Nx3wLEKn/3-m%C3%A9tricas-de-acur%C3%A1cia-do-modelo)
